// <auto-generated />
using System;
using Hurof.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hurof.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322081237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hurof.Api.Entities.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BuzzerLockedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BuzzerLockedByPlayer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GridSize")
                        .HasColumnType("int");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Team1Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Team2Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("WinnerTeam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Hurof.Api.Entities.LetterCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("QuestionIndex")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Row", "Col")
                        .IsUnique();

                    b.ToTable("LetterCells");
                });

            modelBuilder.Entity("Hurof.Api.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Letter", "SortOrder");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Answer = "أ",
                            Letter = "أ",
                            QuestionText = "ما هو الحرف الأول من الأبجدية العربية؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Answer = "أ",
                            Letter = "أ",
                            QuestionText = "أكمل الكلمة: _رض",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Answer = "أ",
                            Letter = "أ",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'أسد'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Answer = "ب",
                            Letter = "ب",
                            QuestionText = "ما هو حرف الجر الدال على الاستعانة؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Answer = "ب",
                            Letter = "ب",
                            QuestionText = "أكمل الكلمة: _يت",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Answer = "ب",
                            Letter = "ب",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'بحر'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Answer = "ت",
                            Letter = "ت",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'تفاح'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Answer = "ت",
                            Letter = "ت",
                            QuestionText = "أكمل الكلمة: _مر",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Answer = "ت",
                            Letter = "ت",
                            QuestionText = "ما الحرف الثالث في الأبجدية العربية؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Answer = "ج",
                            Letter = "ج",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'جبل'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Answer = "ج",
                            Letter = "ج",
                            QuestionText = "أكمل الكلمة: _مل",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Answer = "ج",
                            Letter = "ج",
                            QuestionText = "ما الحرف الذي يبدأ به اسم الجمل بالعربية؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Answer = "ح",
                            Letter = "ح",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'حصان'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Answer = "ح",
                            Letter = "ح",
                            QuestionText = "أكمل الكلمة: _ديقة",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Answer = "ح",
                            Letter = "ح",
                            QuestionText = "ما حرف المد في كلمة 'بحر'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Answer = "خ",
                            Letter = "خ",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'خبز'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Answer = "خ",
                            Letter = "خ",
                            QuestionText = "أكمل الكلمة: _روف",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Answer = "خ",
                            Letter = "خ",
                            QuestionText = "ما الحرف الذي يبدأ به اسم الخروف بالعربية؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Answer = "د",
                            Letter = "د",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'دب'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Answer = "د",
                            Letter = "د",
                            QuestionText = "أكمل الكلمة: _فتر",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Answer = "د",
                            Letter = "د",
                            QuestionText = "ما الحرف الذي يبدأ به 'درس'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Answer = "ر",
                            Letter = "ر",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'رمان'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Answer = "ر",
                            Letter = "ر",
                            QuestionText = "أكمل الكلمة: _جل",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Answer = "ر",
                            Letter = "ر",
                            QuestionText = "ما الحرف الذي يبدأ به 'روضة'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Answer = "ز",
                            Letter = "ز",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'زهرة'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Answer = "ز",
                            Letter = "ز",
                            QuestionText = "أكمل الكلمة: _يتون",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Answer = "ز",
                            Letter = "ز",
                            QuestionText = "ما الحرف الذي يبدأ به 'زرافة'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Answer = "س",
                            Letter = "س",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'سمكة'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            Answer = "س",
                            Letter = "س",
                            QuestionText = "أكمل الكلمة: _ماء",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Answer = "س",
                            Letter = "س",
                            QuestionText = "ما الحرف الذي يبدأ به 'سيارة'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            Answer = "ش",
                            Letter = "ش",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'شجرة'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            Answer = "ش",
                            Letter = "ش",
                            QuestionText = "أكمل الكلمة: _مس",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            Answer = "ش",
                            Letter = "ش",
                            QuestionText = "ما الحرف الذي يبدأ به 'شاطئ'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            Answer = "ص",
                            Letter = "ص",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'صقر'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            Answer = "ص",
                            Letter = "ص",
                            QuestionText = "أكمل الكلمة: _حراء",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            Answer = "ص",
                            Letter = "ص",
                            QuestionText = "ما الحرف الذي يبدأ به 'صوت'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            Answer = "ض",
                            Letter = "ض",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'ضوء'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            Answer = "ض",
                            Letter = "ض",
                            QuestionText = "أكمل الكلمة: _فدع",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            Answer = "ض",
                            Letter = "ض",
                            QuestionText = "ما الحرف الذي يبدأ به 'ضيف'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            Answer = "ط",
                            Letter = "ط",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'طائر'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            Answer = "ط",
                            Letter = "ط",
                            QuestionText = "أكمل الكلمة: _اولة",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            Answer = "ط",
                            Letter = "ط",
                            QuestionText = "ما الحرف الذي يبدأ به 'طريق'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            Answer = "ع",
                            Letter = "ع",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'عصفور'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            Answer = "ع",
                            Letter = "ع",
                            QuestionText = "أكمل الكلمة: _ين",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            Answer = "ع",
                            Letter = "ع",
                            QuestionText = "ما الحرف الذي يبدأ به 'علم'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            Answer = "غ",
                            Letter = "غ",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'غيمة'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            Answer = "غ",
                            Letter = "غ",
                            QuestionText = "أكمل الكلمة: _ابة",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            Answer = "غ",
                            Letter = "غ",
                            QuestionText = "ما الحرف الذي يبدأ به 'غروب'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            Answer = "ف",
                            Letter = "ف",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'فيل'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            Answer = "ف",
                            Letter = "ف",
                            QuestionText = "أكمل الكلمة: _راشة",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            Answer = "ف",
                            Letter = "ف",
                            QuestionText = "ما الحرف الذي يبدأ به 'فصل'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            Answer = "ق",
                            Letter = "ق",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'قمر'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000053"),
                            Answer = "ق",
                            Letter = "ق",
                            QuestionText = "أكمل الكلمة: _طة",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000054"),
                            Answer = "ق",
                            Letter = "ق",
                            QuestionText = "ما الحرف الذي يبدأ به 'قلب'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000055"),
                            Answer = "ك",
                            Letter = "ك",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'كتاب'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000056"),
                            Answer = "ك",
                            Letter = "ك",
                            QuestionText = "أكمل الكلمة: _لب",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000057"),
                            Answer = "ك",
                            Letter = "ك",
                            QuestionText = "ما الحرف الذي يبدأ به 'كرة'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000058"),
                            Answer = "ل",
                            Letter = "ل",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'ليمون'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000059"),
                            Answer = "ل",
                            Letter = "ل",
                            QuestionText = "أكمل الكلمة: _يل",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000060"),
                            Answer = "ل",
                            Letter = "ل",
                            QuestionText = "ما الحرف الذي يبدأ به 'لغة'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000061"),
                            Answer = "م",
                            Letter = "م",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'مدرسة'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000062"),
                            Answer = "م",
                            Letter = "م",
                            QuestionText = "أكمل الكلمة: _اء",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000063"),
                            Answer = "م",
                            Letter = "م",
                            QuestionText = "ما الحرف الذي يبدأ به 'مسجد'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000064"),
                            Answer = "ن",
                            Letter = "ن",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'نجمة'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000065"),
                            Answer = "ن",
                            Letter = "ن",
                            QuestionText = "أكمل الكلمة: _هر",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000066"),
                            Answer = "ن",
                            Letter = "ن",
                            QuestionText = "ما الحرف الذي يبدأ به 'نور'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000067"),
                            Answer = "ه",
                            Letter = "ه",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'هرة'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000068"),
                            Answer = "ه",
                            Letter = "ه",
                            QuestionText = "أكمل الكلمة: _واء",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000069"),
                            Answer = "ه",
                            Letter = "ه",
                            QuestionText = "ما الحرف الذي يبدأ به 'هلال'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000070"),
                            Answer = "و",
                            Letter = "و",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'ورد'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000071"),
                            Answer = "و",
                            Letter = "و",
                            QuestionText = "أكمل الكلمة: _طن",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000072"),
                            Answer = "و",
                            Letter = "و",
                            QuestionText = "ما الحرف الذي يبدأ به 'وقت'؟",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000073"),
                            Answer = "ي",
                            Letter = "ي",
                            QuestionText = "ما الحرف الذي تبدأ به كلمة 'يد'؟",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000074"),
                            Answer = "ي",
                            Letter = "ي",
                            QuestionText = "أكمل الكلمة: _اسمين",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000075"),
                            Answer = "ي",
                            Letter = "ي",
                            QuestionText = "ما الحرف الأخير في الأبجدية العربية؟",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Hurof.Api.Entities.LetterCell", b =>
                {
                    b.HasOne("Hurof.Api.Entities.GameSession", "Session")
                        .WithMany("LetterCells")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Hurof.Api.Entities.GameSession", b =>
                {
                    b.Navigation("LetterCells");
                });
#pragma warning restore 612, 618
        }
    }
}
